Repository f-lab-edu/cafe-guide-book, pull requests merged in 2021-09, with the labels that each got.

#59 [#58] 회원가입시 이메일 중복체크 기능 추가
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/main/java/com/flab/cafeguidebook/exception/DuplicatedEmailException.java
  src/main/java/com/flab/cafeguidebook/mapper/UserMapper.java
  src/main/java/com/flab/cafeguidebook/service/UserService.java
  src/main/java/com/flab/cafeguidebook/service/impl/UserServiceImpl.java
  src/main/resources/mybatis/mapper/UserMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/service/UserServiceTest.java
Labels: enhancement, need review

#64 [#63] Pull Request 및 Issue 템플릿 마크다운 파일 생성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, need review

#73 [#62] RestDocs를 통해 API 문서 자동화 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/CafeServiceTest.java
  src/test/java/com/flab/cafeguidebook/util/ApiDocumentUtils.java
Labels: documentation

#71 [#21] TypeHandler를 통해 Enum 타입으로 회원의 권한 분리
  src/main/java/com/flab/cafeguidebook/config/MyBatisConfig.java
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/main/java/com/flab/cafeguidebook/enumeration/UserType.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/UserTypeHandler.java
Labels: enhancement

#68 [#53] 로그인 체크 기능 AOP 적용
  build.gradle
  src/main/java/com/flab/cafeguidebook/annotation/CurrentUserEmail.java
  src/main/java/com/flab/cafeguidebook/annotation/SignInCheck.java
  src/main/java/com/flab/cafeguidebook/aop/LoginCheckAspect.java
  src/main/java/com/flab/cafeguidebook/aop/SignInCheckAspect.java
  src/main/java/com/flab/cafeguidebook/config/WebConfig.java
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/main/java/com/flab/cafeguidebook/domain/UserSignInRequest.java
  src/main/java/com/flab/cafeguidebook/service/UserService.java
  src/main/java/com/flab/cafeguidebook/service/impl/UserServiceImpl.java
  src/main/java/com/flab/cafeguidebook/util/CurrentUserEmailResolver.java
  src/main/java/com/flab/cafeguidebook/util/ResponseEntityConstants.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
Labels: need review, refactoring

#75 [#61] 비밀번호 업데이트 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/flab/cafeguidebook/aop/LoginCheckAspect.java
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/main/java/com/flab/cafeguidebook/mapper/UserMapper.java
  src/main/java/com/flab/cafeguidebook/service/UserService.java
  src/main/java/com/flab/cafeguidebook/service/impl/UserServiceImpl.java
  src/main/resources/mybatis/mapper/UserMapper.xml
  src/main/resources/static/docs/index.html
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/fixture/UserDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/UserFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/UserServiceTest.java
Labels: enhancement

#96 [#70] feat : 카페 아이디를 DB에서 자동 생성하도록 수정
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
  src/main/java/com/flab/cafeguidebook/dto/CafeDTO.java
  src/main/resources/mybatis/mapper/CafeMapper.xml
  src/test/java/com/flab/cafeguidebook/extension/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/CafeFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeFixtureProvider.java
Labels: need review

#76 [#67] 유저가 자신이 맘에 드는 카페에 추가하기 기능 (좋아요)
  src/docs/asciidoc/index.adoc
  src/main/java/com/flab/cafeguidebook/annotation/CurrentUserId.java
  src/main/java/com/flab/cafeguidebook/aop/SignInCheckAspect.java
  src/main/java/com/flab/cafeguidebook/config/WebConfig.java
  src/main/java/com/flab/cafeguidebook/controller/CafeController.java
  src/main/java/com/flab/cafeguidebook/controller/HeartController.java
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
  src/main/java/com/flab/cafeguidebook/domain/Heart.java
  src/main/java/com/flab/cafeguidebook/domain/User.java
  src/main/java/com/flab/cafeguidebook/dto/CafeDTO.java
  src/main/java/com/flab/cafeguidebook/dto/HeartDTO.java
  src/main/java/com/flab/cafeguidebook/dto/UserDTO.java
  src/main/java/com/flab/cafeguidebook/mapper/HeartMapper.java
  src/main/java/com/flab/cafeguidebook/service/HeartService.java
  src/main/java/com/flab/cafeguidebook/service/UserService.java
  src/main/java/com/flab/cafeguidebook/service/impl/UserServiceImpl.java
  src/main/java/com/flab/cafeguidebook/util/CurrentUserIdResolver.java
  src/main/java/com/flab/cafeguidebook/util/SessionKeys.java
  src/main/resources/mybatis/mapper/HeartMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/HeartControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/extension/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/CafeFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/UserDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/UserFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/UserDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/UserFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/HeartServiceTest.java
  src/test/java/com/flab/cafeguidebook/service/UserServiceTest.java
Labels: enhancement

#74 [#6] 회원탈퇴 구현
  gradlew
  src/docs/asciidoc/index.adoc
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/extension/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/CafeFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/UserServiceTest.java
Labels: enhancement

#87 [#30] 어드민 신규 Cafe에 대한 승인 및 반려 기능 구현
  src/main/java/com/flab/cafeguidebook/controller/CafeController.java
  src/main/java/com/flab/cafeguidebook/enumeration/CafeRegistration.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/CafeRegistrationTypeHandler.java
  src/main/java/com/flab/cafeguidebook/mapper/CafeMapper.java
  src/main/java/com/flab/cafeguidebook/service/CafeService.java
  src/main/resources/mybatis/mapper/CafeMapper.xml
  src/test/java/com/flab/cafeguidebook/service/CafeServiceTest.java
Labels: enhancement

#84 [#51] 카페 메뉴 수정하기 기능
  src/main/java/com/flab/cafeguidebook/controller/MenuController.java
  src/main/java/com/flab/cafeguidebook/converter/MenuConverter.java
  src/main/java/com/flab/cafeguidebook/converter/OptionConverter.java
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
  src/main/java/com/flab/cafeguidebook/domain/Menu.java
  src/main/java/com/flab/cafeguidebook/domain/Option.java
  src/main/java/com/flab/cafeguidebook/dto/MenuDTO.java
  src/main/java/com/flab/cafeguidebook/dto/OptionDTO.java
  src/main/java/com/flab/cafeguidebook/enumeration/MenuGroup.java
  src/main/java/com/flab/cafeguidebook/enumeration/MenuStatus.java
  src/main/java/com/flab/cafeguidebook/enumeration/OptionStatus.java
  src/main/java/com/flab/cafeguidebook/mapper/MenuMapper.java
  src/main/java/com/flab/cafeguidebook/mapper/OptionMapper.java
  src/main/java/com/flab/cafeguidebook/service/MenuService.java
  src/main/java/com/flab/cafeguidebook/service/OptionService.java
  src/main/resources/mybatis/config/mybatis-config.xml
  src/main/resources/mybatis/mapper/MenuMapper.xml
  src/main/resources/mybatis/mapper/OptionMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/MenuControllerTest.java
  src/test/java/com/flab/cafeguidebook/fixture/MenuDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/MenuFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/OptionDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/OptionFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/MenuServiceTest.java
  src/test/java/com/flab/cafeguidebook/service/OptionServiceTest.java
Labels: need review

#77 [#26] 특정 유저가 좋아요 누른 카페 id 조회 기능
  src/main/java/com/flab/cafeguidebook/controller/HeartController.java
  src/main/java/com/flab/cafeguidebook/controller/UserController.java
  src/main/java/com/flab/cafeguidebook/mapper/HeartMapper.java
  src/main/java/com/flab/cafeguidebook/service/HeartService.java
  src/test/java/com/flab/cafeguidebook/controller/HeartControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/service/HeartServiceTest.java
Labels: enhancement

#97 [#38] CD 환경 구축
  build.gradle
Labels: need review

#104 [#103] CI/CD appspec.yml, 스크립트 파일 추가
  appspec.yml
  scripts/script.sh
Labels: need review

#106 [#105] Cafe 도메인 클래스 필요없는 nonnull 제거
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
Labels: bug

#108 [#105] CafeControllerTest 버그 제거
  src/main/java/com/flab/cafeguidebook/dto/CafeDTO.java
  src/main/resources/mybatis/mapper/CafeMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
  src/test/java/com/flab/cafeguidebook/extension/CafeDTOFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/extension/CafeFixtureProvider.java
Labels: bug

#111 [#110] AWS RDS 연동을 위한 릴리즈용 프로퍼티 추가
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
  src/main/resources/application-release.properties
  src/main/resources/application.properties
Labels: enhancement

#114 [#113] MenuMapper 테이블 이름 버그 수정
  src/main/resources/mybatis/mapper/MenuMapper.xml
Labels: bug

#39 [#14] 카페정보 수정하기 및 조회하기 기능 구현
  src/main/java/com/flab/cafeguidebook/config/MyBatisConfig.java
  src/main/java/com/flab/cafeguidebook/controller/CafeController.java
  src/main/java/com/flab/cafeguidebook/converter/CafeConverter.java
  src/main/java/com/flab/cafeguidebook/domain/Cafe.java
  src/main/java/com/flab/cafeguidebook/domain/UpdateCafe.java
  src/main/java/com/flab/cafeguidebook/dto/CafeDTO.java
  src/main/java/com/flab/cafeguidebook/enumeration/CafeCondition.java
  src/main/java/com/flab/cafeguidebook/enumeration/MenuGroup.java
  src/main/java/com/flab/cafeguidebook/enumeration/MenuStatus.java
  src/main/java/com/flab/cafeguidebook/enumeration/OptionStatus.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/CafeConditionTypeHandler.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/CafeRegistrationTypeHandler.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/MenuGroupTypeHandler.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/MenuStatusTypeHandler.java
  src/main/java/com/flab/cafeguidebook/enumeration/handler/OptionStatusTypeHandler.java
  src/main/java/com/flab/cafeguidebook/mapper/CafeMapper.java
  src/main/java/com/flab/cafeguidebook/service/CafeService.java
  src/main/java/com/flab/cafeguidebook/service/MenuService.java
  src/main/resources/application.properties
  src/main/resources/mybatis/config/mybatis-config.xml
  src/main/resources/mybatis/mapper/CafeMapper.xml
  src/main/resources/static/docs/index.html
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/MenuControllerTest.java
  src/test/java/com/flab/cafeguidebook/fixture/CafeDTOListFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/fixture/MenuFixtureProvider.java
  src/test/java/com/flab/cafeguidebook/service/CafeServiceTest.java
Labels: need review

#116 [#115] 테스트 코드 성공하도록 수정
  src/main/java/com/flab/cafeguidebook/controller/ReviewController.java
  src/main/java/com/flab/cafeguidebook/mapper/HeartMapper.java
  src/main/java/com/flab/cafeguidebook/mapper/ReviewMapper.java
  src/main/java/com/flab/cafeguidebook/service/ReviewService.java
  src/main/resources/mybatis/mapper/HeartMapper.xml
  src/main/resources/mybatis/mapper/ReviewMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/HeartControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/ReviewControllerTest.java
  src/test/java/com/flab/cafeguidebook/controller/UserControllerTest.java
  src/test/java/com/flab/cafeguidebook/service/ReviewServiceTest.java
  src/test/java/com/flab/cafeguidebook/service/UserServiceTest.java
Labels: bug

#118 [#105] fix : CafeMapper 테이블 명 수정
  src/main/resources/mybatis/mapper/CafeMapper.xml
  src/test/java/com/flab/cafeguidebook/controller/CafeControllerTest.java
Labels: bug

#120 [#119] appspec.yml 스크립트 파일 경로 수정
  appspec.yml
  scripts/start.sh
Labels: bug

#122 [#121] appspec.yml 스크립트 파일 경로 수정
  appspec.yml
Labels: bug

#124 [#123] script 파일 자바 실행 옵션 수정
  scripts/start.sh
Labels: bug

#126 [#125] build.gradle Log4j2 에러 수정
  build.gradle
  logs/springStudy.log
  src/main/resources/application.properties
  src/main/resources/static/docs/index.html
Labels: bug

#128 [#127] build.gradle에 multi-release attribute 추가
  appspec.yml
  build.gradle
  scripts/start.sh
Labels: bug

#130 [#128] jar -> bootjar로 build.gradle 수정
  build.gradle
Labels: bug
